# Input codes for special units and district units:
# Source: https://directives.crimeisdown.com/diff/efaff1a7e94a8ad642c793993e0d6701c1d276fd/directives/data/a7a57be2-129add9f-15f12-9add-9fea37e07625ed82.html

units <-
  bind_rows(
    tibble::tribble(
      ~unit,                                            ~description,
      "050",                  "Airport Law Enforcement Unit - North",
      "051",                  "Airport Law Enforcement Unit - South",
      "376",                            "Alternate Response Section",
      "411",         "Area Central, Deputy Chief - Bureau of Patrol",
      "413",           "Area North, Deputy Chief - Bureau of Patrol",
      "412",           "Area South, Deputy Chief - Bureau of Patrol",
      "603",                                         "Arson Section",
      "196",               "Asset Forfeiture Investigations Section",
      "168",                                   "Auto Pounds Section",
      "442",                                             "Bomb Unit",
      "443",                            "Bomb Unit - O'Hare Airport",
      "120",                              "Bureau of Administration",
      "180",                                  "Bureau of Detectives",
      "610",                   "Bureau of Detectives - Area Central",
      "620",                     "Bureau of Detectives - Area South",
      "630",                     "Bureau of Detectives - Area North",
      "121",                            "Bureau of Internal Affairs",
      "130",                  "Bureau of Organizational Development",
      "188",                             "Bureau of Organized Crime",
      "142",                                      "Bureau of Patrol",
      "211",                       "Bureau of Patrol - Area Central",
      "212",                         "Bureau of Patrol - Area South",
      "213",                         "Bureau of Patrol - Area North",
      "341",                                           "Canine Unit",
      "171",                                     "Central Detention",
      "606",                       "Central Investigations Division",
      "118",                                     "Chaplains Section",
      "135", "Chicago Alternative Policing Strategy (CAPS) Division",
      "547",                    "Chicago Police Memorial Foundation",
      "176",                         "Communication Operations Unit",
      "261",                                         "Court Section",
      "702",                                     "CTA Security Unit",
      "116",                          "Deployment Operations Center",
      "542",      "Detached Services - Governmental Security Detail",
      "543",              "Detached Services - Miscellaneous Detail",
      "026",                      "District Executive Officers Unit",
      "045",                                "District Reinstatement",
      "124",                       "Education and Training Division",
      "172",                          "Equipment and Supply Section",
      "167",               "Evidence and Recovered Property Section",
      "166",                                "Field Services Section",
      "134",                        "Field Technology Training Unit",
      "122",                                      "Finance Division",
      "173",                                 "Fleet Liaison Section",
      "242",                          "Fleet Management Detail Unit",
      "177",                            "Forensic Services Division",
      "277",       "Forensic Services - Evidence Technician Section",
      "541",                                            "FOP Detail",
      "393",                             "Gang Enforcement Division",
      "193",                           "Gang Investigation Division",
      "311",                       "Gang Enforcement - Area Central",
      "312",                         "Gang Enforcement - Area South",
      "313",                         "Gang Enforcement - Area North",
      "161",                              "General Support Division",
      "060",                                       "Helicopter Unit",
      "123",                              "Human Resources Division",
      "113",            "Independent Police Review Authority (IPRA)",
      "133",                    "Information and Strategic Services",
      "126",                                   "Inspection Division",
      "549",                         "Inspector General Detail Unit",
      "191",                                  "Intelligence Section",
      "384",           "Juvenile Intervention Support Center (JISC)",
      "114",                                 "Legal Affairs Section",
      "608",                     "Major Accident Investigation Unit",
      "129",                  "Management and Labor Affairs Section",
      "059",                                           "Marine Unit",
      "231",                              "Medical Services Section",
      "055",                                   "Mounted Patrol Unit",
      "189",                                    "Narcotics Division",
      "276",                                   "OEMC-Detail Section",
      "115",                    "Office of Crime Control Strategies",
      "140",             "Office of the First Deputy Superintendent",
      "214",                      "Office of Freedom of Information",
      "102",                                "Office of News Affairs",
      "111",                          "Office of the Superintendent",
      "545",                                         "PBPA Sergeant",
      "101",                                          "Police Board",
      "169",                              "Police Documents Section",
      "128",                      "Professional Counseling Division",
      "178",                     "Property Facility Management Unit",
      "125",           "Public Safety Information Technology (PSIT)",
      "701",                         "Public Transportation Section",
      "162",                                      "Records Division",
      "163",                               "Records Inquiry Section",
      "044",                                      "Recruit Training",
      "179",                 "Reproduction and Graphic Arts Section",
      "127",                     "Research and Development Division",
      "441",                            "Special Activities Section",
      "136",                                   "Special Events Unit",
      "141",                            "Special Functions Division",
      "079",                           "Special Investigations Unit",
      "353",               "Special Weapons and Tactics (SWAT) Unit",
      "175",                               "Telecommunications Unit",
      "222",                       "Timekeeping Unit - Headquarters",
      "145",                                       "Traffic Section",
      "148",                                    "Traffic Court Unit",
      "154",                           "Traffic Safety and Training",
      "704",                                 "Transit Security Unit",
      "241",                            "Troubled Buildings Section",
      "192",                    "Vice and Asset Forfeiture Division",
      "711",                 "Violence Reduction Initiative - North",
      "712",                 "Violence Reduction Initiative - South",
      "184",                           "Youth Investigation Section"
    ) %>%
      mutate(type = "special"),
    tibble::tribble(
      ~unit,                  ~description,
      "001",        "District 1 - Central", 
      "002",      "District 2 - Wentworth", 
      "003", "District 3 - Grand Crossing", 
      "004",  "District 4 - South Chicago", 
      "005",        "District 5 - Calumet", 
      "006",        "District 6 - Gresham",
      "007",      "District 7 - Englewood", 
      "008",   "District 8 - Chicago Lawn", 
      "009",        "District 9 - Deering", 
      "010",         "District 10 - Ogden", 
      "011",      "District 11 - Harrison",
      "012",      "District 12 - Near West",
      "014",    "District 14 - Shakespeare",
      "015",         "District 15 - Austin",
      "016", "District 16 - Jefferson Park",
      "017",    "District 17 - Albany Park",
      "018",     "District 18 - Near North",
      "019",      "District 19 - Town Hall",
      "020",        "District 20 - Lincoln",
      "022",    "District 22 - Morgan Park",
      "024",    "District 24 - Rogers Park",
      "025",  "District 25 - Grand Central"
    ) %>%
      mutate(type = "district")
  )

